### ISSUE TITLE
In log file: Error: certificate has expired

### ISSUE THREAD

**Issue by TurtleHunter** [KYDronePilot/SpaceEye#47]
While looking at logs for another issue I'm having (#33), I noticed the below section stating that the DNS handler was experiencing an error related to an expired certification:

[2022-06-06 16:15:38.353] [info] (main)                        Get satellite config request received
[2022-06-06 16:15:38.356] [debug] (main)                        Windows taskbar update cmd exited with: 0
[2022-06-06 16:15:38.360] [info] (main)                        Current view request received
[2022-06-06 16:15:38.361] [debug] (app-config-store)            Current view ID retrieved: 1
[2022-06-06 16:15:38.362] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.363] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.363] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.366] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.368] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.369] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.371] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.374] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.374] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.376] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.378] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.379] [info] (main)                        Download thumbnail request received
[2022-06-06 16:15:38.382] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:38.384] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:38.384] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:38.385] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:38.386] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:38.387] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:38.388] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:38.389] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:38.391] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:38.391] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:38.392] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:38.420] [info] (dns-handler)                 All failed DNS HEAD probe responses:
[2022-06-06 16:15:38.421] [info] (dns-handler)                 CERT_HAS_EXPIRED
certificate has expired
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
[2022-06-06 16:15:38.421] [info] (dns-handler)                 CERT_HAS_EXPIRED
certificate has expired
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
[2022-06-06 16:15:38.421] [error] (main)                        Error while downloading thumbnail: undefined
All DNS HEAD probes failed. Check logs.
RequestError: All DNS HEAD probes failed. Check logs.
    at C:\Program Files\WindowsApps\43181KYDronePilot.SpaceEye_1.2.7.0_x64__vrq1rw3s6b9wj\app\resources\app.asar\dist\main.js:278:237562
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[2022-06-06 16:15:39.829] [info] (main)                        Reload request received for view: 1
[2022-06-06 16:15:39.830] [info] (wallpaper-manager)           Update triggered by 0, lock acquisition succeeded
[2022-06-06 16:15:39.830] [debug] (wallpaper-manager)           Entering update pipeline
[2022-06-06 16:15:39.830] [debug] (app-config-store)            Current view ID retrieved: 1
[2022-06-06 16:15:39.831] [debug] (wallpaper-manager)           Determining which image is needed to update
[2022-06-06 16:15:39.831] [debug] (wallpaper-manager)           All monitors: [ 2528732444, 2779098405 ]
[2022-06-06 16:15:39.831] [debug] (wallpaper-manager)           Optimal image for view "1": 6
[2022-06-06 16:15:39.832] [debug] (downloaded-image)            All files in images dir: [ '6-1654542712859.jpg', '6-1654545164927.jpg', '6-1654546420156.jpg' ]
[2022-06-06 16:15:39.832] [debug] (downloaded-image)            All image files: [ '6-1654542712859.jpg', '6-1654545164927.jpg', '6-1654546420156.jpg' ]
[2022-06-06 16:15:39.833] [info] (wallpaper-manager)           New image must be downloaded
[2022-06-06 16:15:39.833] [debug] (image-downloader)            Downloading image to: C:\Users\Samuel\AppData\Roaming\space-eye\downloaded_images\6-1654546539833.jpg.download
[2022-06-06 16:15:39.834] [debug] (dns-handler)                 Skipping DNS probing on imagery.spaceeye.app
[2022-06-06 16:15:40.158] [debug] (main)                        Heartbeat triggered
[2022-06-06 16:15:40.158] [info] (wallpaper-manager)           Update triggered by 2, lock acquisition failed
[2022-06-06 16:15:40.199] [debug] (image-downloader)            Successfully downloaded image: 6

**Comment by TurtleHunter** [comment]
> @TurtleHunter where is this log file located? I've had a little root around but didn't find it. SpaceEye has stopped downloading new imagery/thumbnails for me.

I don't recall. I've just been using Display Fusion to load the image from a url every x minutes. I'll try and post my settings tonight, ping me tomorrow if it doesn't happen.

**Comment by TurtleHunter** [comment]
@cheeseandjamsandwich 
In Display Fusion, under Options, click Desktop Wallpaper.
Under Wallpaper Souce check Slideshow, change Source to select Load Image from URL, Center, 11 minute interval (or whatever). I use this URL for full disk:
https://cdn.star.nesdis.noaa.gov/GOES16/ABI/FD/GEOCOLOR/5424x5424.jpg
To the right, Under Monitor Settings, Color: Background color is black
Adjustments tab: I have Scale 50%, Move Horizontal -400 pixels, and Move Vertical 1200 pixels.
Info tab: I put a timestamp by: Add Info Tag > General >  Date/Time Generated although File Date Created might be better?
I have my font set to Courier New size 10 white text italic.
Wallpaper Settings: I have everything checked.

**Comment by johnsoe2** [comment]
For my install, the log is located at:
\Users\user_name\AppData\Local\Packages\43181KYDronePilot.SpaceEye_vrq1rw3s6b9wj\LocalCache\Roaming\space-eye\logs

I have "certificate has expired" errors going back over a month now.

**Comment by cheeseandjamsandwich** [comment]
Thanks
I found my log in
`AppData\Roaming\space-eye\logs`
Same, same...  `message: 'certificate has expired',`

I tried accessing Himawari's image directly
`https://172.67.177.103/himawari/full-disk/8k.jpg`
but the computer said no...  
```
This site can’t provide a secure connection
172.67.177.103 uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```
Perhaps you need a certificate to access the data directly...

I'll check out DisplayFusion again...  haven't played with that for years.
But obvs would still love Space-Eye to get a little fix.

**Comment by TurtleHunter** [comment]
I agree I'd rather be using SpaceEye as well.

Try this URL
https://rammb.cira.colostate.edu/ramsdis/online/images/latest_hi_res/himawari-8/full_disk_ahi_natural_color.jpg

Found it here:
https://rammb.cira.colostate.edu/ramsdis/online/himawari-8.asp

**Comment by KYDronePilot** [comment]
@cheeseandjamsandwich try accessing https://imagery.spaceeye.app/himawari/full-disk/8k.jpg directly and see if that works

**Comment by KYDronePilot** [comment]
@TurtleHunter @cheeseandjamsandwich @johnsoe2 give SpaceEye a try now. I think I've got it fixed. Switched to a different SSL certificate authority.

**Comment by cheeseandjamsandwich** [comment]
> @TurtleHunter @cheeseandjamsandwich @johnsoe2 give SpaceEye a try now. I think I've got it fixed. Switched to a different SSL certificate authority.

It's working again!!!

Many thanks again @KYDronePilot!
I appreciate the time you spent fixing it.

My wallpaper is now showing the up to date view of my side of the Earth.  
Thanks.

**Comment by KYDronePilot** [comment]
Please let me know if this issue ever comes up again!
