### ISSUE TITLE
error downloading

### ISSUE THREAD

**Issue by Carlo618Blanco** [KYDronePilot/SpaceEye#66]
Thanks

**Comment by RichL2004** [comment]
Error downloading issue has returned. All satellites showing error. Looks like the last image was downloaded around 5:00 PM EST according to the file time stamp...... Anything else, let us know and I'll pull a log file if needed.  Thanks, Rich

**Comment by maxEntropyProd** [comment]
same here. error downloading

**Comment by ggariepy** [comment]
Agreed, same here too.  A visit to https://spaceeye.app/ is displaying a certificate error.  I'd be willing to bet that's the problem.

**Comment by ggariepy** [comment]
2023-11-27 14:18:47.435] [error] (wallpaper-manager)           Error while updating. Invalidating lock. {
  message: 'certificate has expired',
  name: 'Error',
  stack: 'Error: certificate has expired\n' +
    '    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)\n' +
    '    at TLSSocket.emit (events.js:223:5)\n' +
    '    at TLSSocket._finishInit (_tls_wrap.js:794:8)\n' +
    '    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)',
  config: {
    url: 'https://172.67.177.103/goes-16/full-disk/8k.jpg',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'SpaceEye/1.2.7 (ms)',
      Host: 'imagery.spaceeye.app'
    },
    transformRequest: [
      '[function] function(e,t){return i(t,"Accept"),i(t,"Content-Type"),n.isFormData(e)||n.isArrayBuffer(e)||n.isBuffer(e)||n.isStream(e)||n.isFile(e)||n.isBlob(e)?e:n.isArrayBufferView(e)?e.buffer:n.isURLSearchParams(e)?(s(t,"application/x-www-form-urlencoded;charset=utf-8"),e.toString()):n.isObject(e)?(s(t,"application/json;charset=utf-8"),JSON.stringify(e)):e}'
    ],
    transformResponse: [
      '[function] function(e){if("string"==typeof e)try{e=JSON.parse(e)}catch(e){}return e}'
    ],
    timeout: 0,
    adapter: '[function] function(e){return new Promise((function(t,r){var y=function(e){t(e)},g=function(e){r(e)},v=e.data,w=e.headers;if(w["User-Agent"]||w["user-agent"]||(w["User-Agent"]="axios/"+f.version),v&&!n.isStream(v)){if(Buffer.isBuffer(v));else if(n.isArrayBuffer(v))v=Buffer.from(new Uint8Array(v));else{if(!n.isString(v))return g(p("Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream",e));v=Buffer.from(v,"utf-8")}w["Content-Length"]=v.length}var D=void 0;e.auth&&(D=(e.auth.username||"")+":"+(e.auth.password||""));var M=a(e.baseURL,e.url),E=d.parse(M),b=E.protocol||"http:";if(!D&&E.auth){var L=E.auth.split(":");D=(L[0]||"")+":"+(L[1]||"")}D&&delete w.Authorization;var S=_.test(b),k=S?e.httpsAgent:e.httpAgent,x={path:s(E.path,e.params,e.paramsSerializer).replace(/^\\?/,""),method:e.method.toUpperCase(),headers:w,agent:k,agents:{http:e.httpAgent,https:e.httpsAgent},auth:D};e.socketPath?x.socketPath=e.socketPath:(x.hostname=E.hostname,x.port=E.port);var T,A=e.proxy;if(!A&&!1!==A){var Y=b.slice(0,-1)+"_proxy",C=process.env[Y]||process.env[Y.toUpperCase()];if(C){var P=d.parse(C),O=process.env.no_proxy||process.env.NO_PROXY,F=!0;if(O)F=!O.split(",").map((function(e){return e.trim()})).some((function(e){return!!e&&("*"===e||("."===e[0]&&E.hostname.substr(E.hostname.length-e.length)===e||E.hostname===e))}));if(F&&(A={host:P.hostname,port:P.port},P.auth)){var j=P.auth.split(":");A.auth={username:j[0],password:j[1]}}}}if(A&&(x.hostname=A.host,x.host=A.host,x.headers.host=E.hostname+(E.port?":"+E.port:""),x.port=A.port,x.path=b+"//"+E.hostname+(E.port?":"+E.port:"")+x.path,A.auth)){var I=Buffer.from(A.auth.username+":"+A.auth.password,"utf8").toString("base64");x.headers["Proxy-Authorization"]="Basic "+I}var N=S&&(!A||_.test(A.protocol));e.transport?T=e.transport:0===e.maxRedirects?T=N?u:o:(e.maxRedirects&&(x.maxRedirects=e.maxRedirects),T=N?l:c),e.maxContentLength&&e.maxContentLength>-1&&(x.maxBodyLength=e.maxContentLength);var R=T.request(x,(function(t){if(!R.aborted){var r=t;switch(t.headers["content-encoding"]){case"gzip":case"compress":case"deflate":r=204===t.statusCode?r:r.pipe(h.createUnzip()),delete t.headers["content-encoding"]}var n=t.req||R,a={status:t.statusCode,statusText:t.statusMessage,headers:t.headers,config:e,request:n};if("stream"===e.responseType)a.data=r,i(y,g,a);else{var s=[];r.on("data",(function(t){s.push(t),e.maxContentLength>-1&&Buffer.concat(s).length>e.maxContentLength&&(r.destroy(),g(p("maxContentLength size of "+e.maxContentLength+" exceeded",e,null,n)))})),r.on("error",(function(t){R.aborted||g(m(t,e,null,n))})),r.on("end",(function(){var t=Buffer.concat(s);"arraybuffer"!==e.responseType&&(t=t.toString(e.responseEncoding)),a.data=t,i(y,g,a)}))}}}));R.on("error",(function(t){R.aborted||g(m(t,e,null,R))})),e.timeout&&R.setTimeout(e.timeout,(function(){R.abort(),g(p("timeout of "+e.timeout+"ms exceeded",e,"ECONNABORTED",R))})),e.cancelToken&&e.cancelToken.promise.then((function(e){R.aborted||(R.abort(),g(e))})),n.isStream(v)?v.on("error",(function(t){g(m(t,e,null,R))})).pipe(R):R.end(v)}))}',
    responseType: 'stream',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: '[function] function(e){return e>=200&&e<300}',
    cancelToken: { promise: {} }
  },
  code: 'CERT_HAS_EXPIRED'
}

**Comment by KYDronePilot** [comment]
I think I've got a fix in place. Please confirm if the issue no longer exists.

**Comment by ggariepy** [comment]
Sadly, no, it's not fixed.

Here's a snippet from the log.  Times are in EST.

[2023-11-30 22:15:20.492] [error] (wallpaper-manager)           Error while
updating. Invalidating lock. {
  message: 'certificate has expired',
  name: 'Error',
  stack: 'Error: certificate has expired\n' +
    '    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)\n' +
    '    at TLSSocket.emit (events.js:223:5)\n' +
    '    at TLSSocket._finishInit (_tls_wrap.js:794:8)\n' +
    '    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)',
  config: {
    url: 'https://104.21.43.88/goes-16/continental-us/2k.jpg',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'SpaceEye/1.2.7 (ms)',
      Host: 'imagery.spaceeye.app'
    },

**Comment by KYDronePilot** [comment]
Try now

**Comment by ggariepy** [comment]
All fixed!  Thank you for taking the time to do this!  BTW, if I were you, I would consider making this a paid app, I think it's worth it.

**Comment by RichL2004** [comment]
Looks okay this morning.... Thanks Michael. Rich

**Comment by maxEntropyProd** [comment]
👍
